[package]
name = "my-pso"
version = "0.1.0"
entrypoint = "template/main.typ"
description = "Auto-incrementing homework template"
authors = ["Maksim"]

[template]
path = "template"
entrypoint = "main.typ"
